@host = http://localhost:5290

### 1. Create a new bus

POST {{host}}/api/bus
Content-Type: application/json

{
"busName": "Green Line",
"busNumber": "DHK-1234"
}

### 2. Get all buses

GET {{host}}/api/bus
Accept: application/json

### 3. Get a bus by ID

GET {{host}}/api/bus/f18bf6d2-a242-4110-85a0-8a45003e1e60
Accept: application/json


### 4. Update a bus

# Replace the ID with an existing BusId

PUT {{host}}/api/bus/a9d0b755-d194-46b7-96d4-5203e3437635
Content-Type: application/json

{
"busName": "Prince Express",
"busNumber": "DHK-9999"
}

### 6. Delete a bus by BusId

DELETE {{host}}/api/bus/f18bf6d2-a242-4110-85a0-8a45003e1e60

